-- Criado por mockaroo.com
insert into cars (brand, model, price, color, carYear, transmission) values ('Suzuki', 'Grand Vitara', 59448.46, 'Red', 1999, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Lamborghini', 'Gallardo', 45801.03, 'Violet', 2006, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Ford', 'E-Series', 48897.3, 'Maroon', 2002, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Mitsubishi', 'Galant', 28088.06, 'Aquamarine', 1996, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Mitsubishi', 'Outlander', 14225.64, 'Fuscia', 2004, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Mercury', 'Tracer', 49151.45, 'Mauv', 1991, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Ford', 'Crown Victoria', 27795.88, 'Yellow', 2011, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Chevrolet', 'Beretta', 17486.13, 'Aquamarine', 1994, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Lotus', 'Evora', 47172.79, 'Maroon', 2012, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Isuzu', 'i-280', 48887.37, 'Pink', 2006, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Pontiac', 'Trans Sport', 24904.72, 'Puce', 1996, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Hyundai', 'Elantra', 18730.48, 'Teal', 1993, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Volvo', 'C30', 46052.08, 'Turquoise', 2012, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Buick', 'Reatta', 21745.29, 'Teal', 1991, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Toyota', 'Solara', 28172.69, 'Indigo', 2007, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Volkswagen', 'New Beetle', 37164.11, 'Violet', 2002, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Audi', 'S6', 11856.42, 'Crimson', 2002, 'manual');
insert into cars (brand, model, price, color, carYear, transmission) values ('Pontiac', 'Firebird', 52703.18, 'Teal', 1984, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Volkswagen', 'Touareg 2', 50113.09, 'Green', 2009, 'automatico');
insert into cars (brand, model, price, color, carYear, transmission) values ('Jeep', 'Liberty', 12018.81, 'Green', 2012, 'automatico');